// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SigaDocIntegracao.Web.Persistence;

#nullable disable

namespace SigaDocIntegracao.Web.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241003183259_PRD-1")]
    partial class PRD1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SigaDocIntegracao.Web.Models.ModuloEmail.DocAssinadoEmailHistoricoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_DOCUMENTO_NOME");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean")
                        .HasColumnName("FLG_STATUS_ENVIADO");

                    b.HasKey("Id");

                    b.ToTable("CAD_MODELO_EMAIL_HIST");
                });

            modelBuilder.Entity("SigaDocIntegracao.Web.Models.ModuloEmail.ExModeloEmailParamModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_ASSUNTO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("FLG_STATUS_ATIVO");

                    b.Property<string>("ConteudoEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_CONTEUDO_EMAIL");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DTH_CRIACAO_NOT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DTH_INICIO_ENVIO");

                    b.Property<DateTime>("DataUltimoProcessamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DTH_ULTIMO_PROCESSAMENTO");

                    b.Property<string>("DescricaoModelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_DESCRICAO_MODELO");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_DESTINATARIOS_EMAILS");

                    b.Property<string>("IdSigaDoc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ID_SIGA_DOC");

                    b.Property<string>("NomeNot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TXT_NOME_NOT");

                    b.HasKey("Id");

                    b.ToTable("CAD_MODELO_NOTIF_EMAIL");
                });
#pragma warning restore 612, 618
        }
    }
}
