//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class @base {
    
    private baseCargo[] cargosField;
    
    private baseFuncao[] funcoesField;
    
    private baseOrgao[] orgaosField;
    
    private baseLotacao[] lotacoesField;
    
    private basePessoa[] pessoasField;
    
    private string orgaoUsuarioField;
    
    private string dataHoraField;
    
    private int versaoField;
    
    private bool versaoFieldSpecified;
    
    private string aditionalEmailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("cargo", IsNullable=false)]
    public baseCargo[] cargos {
        get {
            return this.cargosField;
        }
        set {
            this.cargosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("funcao", IsNullable=false)]
    public baseFuncao[] funcoes {
        get {
            return this.funcoesField;
        }
        set {
            this.funcoesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("orgao", IsNullable=false)]
    public baseOrgao[] orgaos {
        get {
            return this.orgaosField;
        }
        set {
            this.orgaosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("lotacao", IsNullable=false)]
    public baseLotacao[] lotacoes {
        get {
            return this.lotacoesField;
        }
        set {
            this.lotacoesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pessoa", IsNullable=false)]
    public basePessoa[] pessoas {
        get {
            return this.pessoasField;
        }
        set {
            this.pessoasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string orgaoUsuario {
        get {
            return this.orgaoUsuarioField;
        }
        set {
            this.orgaoUsuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataHora {
        get {
            return this.dataHoraField;
        }
        set {
            this.dataHoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool versaoSpecified {
        get {
            return this.versaoFieldSpecified;
        }
        set {
            this.versaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aditionalEmails {
        get {
            return this.aditionalEmailsField;
        }
        set {
            this.aditionalEmailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class baseCargo {
    
    private short idField;
    
    private bool idFieldSpecified;
    
    private string nomeField;
    
    private string siglaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sigla {
        get {
            return this.siglaField;
        }
        set {
            this.siglaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class baseFuncao {
    
    private short idField;
    
    private bool idFieldSpecified;
    
    private string nomeField;
    
    private string siglaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short id
    {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sigla {
        get {
            return this.siglaField;
        }
        set {
            this.siglaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class baseOrgao {
    
    private short idField;
    
    private bool idFieldSpecified;
    
    private string nomeField;
    
    private string siglaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sigla {
        get {
            return this.siglaField;
        }
        set {
            this.siglaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class baseLotacao {
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string nomeField;
    
    private string idPaiField;
    
    private string siglaField;
    
    private string tipoLotacaoField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idPai {
        get {
            return this.idPaiField;
        }
        set {
            this.idPaiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sigla {
        get {
            return this.siglaField;
        }
        set {
            this.siglaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoLotacao {
        get {
            return this.tipoLotacaoField;
        }
        set {
            this.tipoLotacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class basePessoa {
    
    private basePessoaPapel[] papelField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private long cpfField;
    
    private bool cpfFieldSpecified;
    
    private string nomeField;
    
    private string dtNascimentoField;
    
    private bool dtNascimentoFieldSpecified;
    
    private string nacionalidadeField;
    
    private string ruaField;
    
    private string bairroField;
    
    private string cidadeField;
    
    private string ufField;
    
    private int cepField;
    
    private bool cepFieldSpecified;
    
    private string telefoneField;
    
    private string naturalidadeField;
    
    private string tipoSanguineoField;
    
    private string grauInstrucaoField;
    
    private int matriculaField;
    
    private bool matriculaFieldSpecified;
    
    private string dtInicioExercicioField;
    
    private bool dtInicioExercicioFieldSpecified;
    
    private int atoNomeacaoField;
    
    private bool atoNomeacaoFieldSpecified;
    
    private int dtNomeacaoField;
    
    private bool dtNomeacaoFieldSpecified;
    
    private string dtAtoPublicacaoField;
    
    private int dtPosseField;
    
    private bool dtPosseFieldSpecified;
    
    private int cargoField;
    
    private bool cargoFieldSpecified;
    
    private string padraoReferenciaField;
    
    private int situacaoField;
    
    private bool situacaoFieldSpecified;
    
    private long lotacaoField;
    
    private bool lotacaoFieldSpecified;
    
    private string rgField;
    
    private bool rgFieldSpecified;
    
    private string rgOrgaoField;
    
    private string rgUfField;
    
    private string rgDtExpField;
    
    private bool rgDtExpFieldSpecified;
    
    private string siglaField;
    
    private string emailField;
    
    private string funcaoConfiancaField;
    
    private string tipoField;
    
    private string sexoField;
    
    private int estCivilField;
    
    private bool estCivilFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("papel")]
    public basePessoaPapel[] papel {
        get {
            return this.papelField;
        }
        set {
            this.papelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long cpf {
        get {
            return this.cpfField;
        }
        set {
            this.cpfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cpfSpecified {
        get {
            return this.cpfFieldSpecified;
        }
        set {
            this.cpfFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dtNascimento {
        get {
            return this.dtNascimentoField;
        }
        set {
            this.dtNascimentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtNascimentoSpecified {
        get {
            return this.dtNascimentoFieldSpecified;
        }
        set {
            this.dtNascimentoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nacionalidade {
        get {
            return this.nacionalidadeField;
        }
        set {
            this.nacionalidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rua {
        get {
            return this.ruaField;
        }
        set {
            this.ruaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bairro {
        get {
            return this.bairroField;
        }
        set {
            this.bairroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cidade {
        get {
            return this.cidadeField;
        }
        set {
            this.cidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uf {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cep {
        get {
            return this.cepField;
        }
        set {
            this.cepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cepSpecified {
        get {
            return this.cepFieldSpecified;
        }
        set {
            this.cepFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telefone {
        get {
            return this.telefoneField;
        }
        set {
            this.telefoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string naturalidade {
        get {
            return this.naturalidadeField;
        }
        set {
            this.naturalidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoSanguineo {
        get {
            return this.tipoSanguineoField;
        }
        set {
            this.tipoSanguineoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string grauInstrucao {
        get {
            return this.grauInstrucaoField;
        }
        set {
            this.grauInstrucaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool matriculaSpecified {
        get {
            return this.matriculaFieldSpecified;
        }
        set {
            this.matriculaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dtInicioExercicio {
        get {
            return this.dtInicioExercicioField;
        }
        set {
            this.dtInicioExercicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtInicioExercicioSpecified {
        get {
            return this.dtInicioExercicioFieldSpecified;
        }
        set {
            this.dtInicioExercicioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int atoNomeacao {
        get {
            return this.atoNomeacaoField;
        }
        set {
            this.atoNomeacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool atoNomeacaoSpecified {
        get {
            return this.atoNomeacaoFieldSpecified;
        }
        set {
            this.atoNomeacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int dtNomeacao {
        get {
            return this.dtNomeacaoField;
        }
        set {
            this.dtNomeacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtNomeacaoSpecified {
        get {
            return this.dtNomeacaoFieldSpecified;
        }
        set {
            this.dtNomeacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dtAtoPublicacao {
        get {
            return this.dtAtoPublicacaoField;
        }
        set {
            this.dtAtoPublicacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int dtPosse {
        get {
            return this.dtPosseField;
        }
        set {
            this.dtPosseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtPosseSpecified {
        get {
            return this.dtPosseFieldSpecified;
        }
        set {
            this.dtPosseFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cargoSpecified {
        get {
            return this.cargoFieldSpecified;
        }
        set {
            this.cargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string padraoReferencia {
        get {
            return this.padraoReferenciaField;
        }
        set {
            this.padraoReferenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int situacao {
        get {
            return this.situacaoField;
        }
        set {
            this.situacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool situacaoSpecified {
        get {
            return this.situacaoFieldSpecified;
        }
        set {
            this.situacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lotacao {
        get {
            return this.lotacaoField;
        }
        set {
            this.lotacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lotacaoSpecified {
        get {
            return this.lotacaoFieldSpecified;
        }
        set {
            this.lotacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rg {
        get {
            return this.rgField;
        }
        set {
            this.rgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rgSpecified {
        get {
            return this.rgFieldSpecified;
        }
        set {
            this.rgFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rgOrgao {
        get {
            return this.rgOrgaoField;
        }
        set {
            this.rgOrgaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rgUf {
        get {
            return this.rgUfField;
        }
        set {
            this.rgUfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rgDtExp {
        get {
            return this.rgDtExpField;
        }
        set {
            this.rgDtExpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rgDtExpSpecified {
        get {
            return this.rgDtExpFieldSpecified;
        }
        set {
            this.rgDtExpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sigla {
        get {
            return this.siglaField;
        }
        set {
            this.siglaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string funcaoConfianca {
        get {
            return this.funcaoConfiancaField;
        }
        set {
            this.funcaoConfiancaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sexo {
        get {
            return this.sexoField;
        }
        set {
            this.sexoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int estCivil {
        get {
            return this.estCivilField;
        }
        set {
            this.estCivilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estCivilSpecified {
        get {
            return this.estCivilFieldSpecified;
        }
        set {
            this.estCivilFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class basePessoaPapel {
    
    private short idField;
    
    private bool idFieldSpecified;
    
    private string tipoField;
    
    private int cargoField;
    
    private bool cargoFieldSpecified;
    
    private string funcaoConfiancaField;
    
    private long lotacaoField;
    
    private bool lotacaoFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cargoSpecified {
        get {
            return this.cargoFieldSpecified;
        }
        set {
            this.cargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string funcaoConfianca {
        get {
            return this.funcaoConfiancaField;
        }
        set {
            this.funcaoConfiancaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lotacao {
        get {
            return this.lotacaoField;
        }
        set {
            this.lotacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lotacaoSpecified {
        get {
            return this.lotacaoFieldSpecified;
        }
        set {
            this.lotacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
